### ISSUE TITLE
value error

### ISSUE THREAD

**Issue by Abhinavk910** [Dartum08/Automated-Image-Captioning#1]
model.fit(train_gen, epochs=1, steps_per_epoch=steps, verbose=1, validation_data=dev_gen, validation_steps=dev_steps, callbacks=[model_checkpoint_callback])

ValueError: in user code:

    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:541 train_step  **
        self.trainable_variables)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:1804 _minimize
        trainable_variables))
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:521 _aggregate_gradients
        filtered_grads_and_vars = _filter_grads(grads_and_vars)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:1219 _filter_grads
        ([v.name for _, v in grads_and_vars],))

    ValueError: No gradients provided for any variable: ['dense_3/kernel:0', 'dense_3/bias:0', 'lstm_1/lstm_cell_1/kernel:0', 'lstm_1/lstm_cell_1/recurrent_kernel:0', 'lstm_1/lstm_cell_1/bias:0', 'dense_4/kernel:0', 'dense_4/bias:0', 'dense_5/kernel:0', 'dense_5/bias:0'].

**Comment by Dartum08** [comment]
It worked fine for me. Make sure you have loaded all the required libraries. I have created a file for the libraries that I have used in this problem, do check it. Because I have also encountered this error, what I tried was changing this : 'from tensorflow.keras.layers import Dense'  to  'from keras.layers import Dense' this. In my case, it depends on how you have loaded your libraries. Maybe this is why your error is coming.
 Also, you can try google the error, you may find very promising answers there.
Still anything doesn't work, feel free to ping me.

**Comment by Abhinavk910** [comment]
Thanks, you were correct. There is some import which is from Keras and some are from TensorFlow. That's causing this problem.

**Comment by Dartum08** [comment]
Glad I can be of any help!
